[package]
authors = ["Nikola Stoyanov <ns.barzakov@gmail.com>"]
name = "parallel-dfs"
version = "0.1.0"

[dependencies]
crossbeam = "0.3.2"
rand = "0.5.0"
rayon = "1.0.1"
spin = { version = "0.4.8", default_features = false }
structopt = "0.2.10"
